name: angkasapp
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0-43.0.dev <4.0.0'

dependencies:
  http: ^1.1.2
  tuple: 2.0.2
  image: ^3.0.1
  intl: ^0.17.0
  flutter:
    sdk: flutter
  flutter_image: 4.1.9
  country_flags: ^2.1.1
  flutter_local_notifications: ^16.3.0
  flutter_timezone: ^1.0.8
  fluttertoast: ^8.2.4
  rxdart: ^0.27.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  hive_ui: ^1.0.14
  path_provider: ^2.1.2

  build_runner: ^2.4.8

  cupertino_icons: ^1.0.2
  flutter_map: ^6.0.1
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
  - assets/Pin.png
  - assets/T1_L1.jpg
  - assets/T1_L2.jpg
  - assets/T2_L1.jpg
  - assets/T2_L2.jpg
  - assets/T3_1_Arrival.jpg
  - assets/T3_2_BoardingLounge.jpg
  - assets/T3_3_CheckInArea.jpg
  - assets/T3_4_GedungParkir&ExhibitionHallDomestic_M.jpg
  - assets/T3_5_GedungParkir&ExhibitionHallInternational.jpg
  - assets/T2_L1_Path.png
  - assets/T2_L2_Path.png
